### ISSUE TITLE
On demand validation

### ISSUE THREAD

**Issue by dhimmel** [idrdex/stargeo#5]
Oftentimes I want to see the tags already applied to a specific dataset. Sometimes I may want to validate or modify those tags. Othertimes, I make a mistake and want an easy way to modify my tag.

@idrdex and I discussed a potential mechanism where by clicking on a tag label, a dataset can be retagged/validated. Thoughts?

**Comment by idrdex** [comment]
Moved to https://github.com/idrdex/star-django/issues
