### ISSUE TITLE
Resolving a tag name-description conflict

### ISSUE THREAD

**Issue by dhimmel** [idrdex/stargeo#7]
name: `PC_Control`
description: `Adjacent normal prostate tissue from PC patients`

The name implies that the tag should cover all samples from patients without prostate cancer. The description indicates that the tag is for PC cases but from normal tissue.

This also brings up the outstanding issue of how to deal to healthy tissue from diseased patients.

Suggestions?

**Comment by idrdex** [comment]
Moved to https://github.com/idrdex/star-django/issues
